# Generated by Django 4.2.3 on 2023-09-19 20:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producthit',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 20, 0, 3, 44, 947992), verbose_name='زمان مشاهده'),
        ),
    ]
