# Generated by Django 4.2.3 on 2023-09-19 20:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_module', '0001_initial'),
        ('product_module', '0004_alter_producthit_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hits_product',
            field=models.ManyToManyField(blank=True, related_name='product_hits', through='product_module.ProductHit', to='home_module.ipaddress', verbose_name='بازدیدکننده ها'),
        ),
        migrations.AlterField(
            model_name='producthit',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 20, 0, 18, 30, 583610), verbose_name='زمان مشاهده'),
        ),
    ]
