# Generated by Django 4.2.3 on 2023-09-20 20:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0007_alter_producthit_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producthit',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 20, 23, 57, 35, 668148), verbose_name='زمان مشاهده'),
        ),
    ]
