# Generated by Django 4.2.3 on 2023-09-24 20:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0011_alter_producthit_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brand_product', to='product_module.productbrand', verbose_name='برند'),
        ),
        migrations.AlterField(
            model_name='producthit',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 24, 23, 47, 22, 882630), verbose_name='زمان مشاهده'),
        ),
    ]
