# Generated by Django 4.2.3 on 2023-10-15 16:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0012_alter_product_brand_alter_producthit_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producthit',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 15, 20, 11, 55, 674045), verbose_name='زمان مشاهده'),
        ),
    ]
