# Generated by Django 4.2.3 on 2023-10-26 18:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0013_alter_producthit_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-id'], 'verbose_name': 'محصول', 'verbose_name_plural': 'محصولات'},
        ),
        migrations.AlterField(
            model_name='producthit',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 26, 22, 4, 56, 384565), verbose_name='زمان مشاهده'),
        ),
    ]
