# Generated by Django 4.2.3 on 2023-10-26 18:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0015_alter_producthit_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producthit',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 26, 22, 9, 15, 517936), verbose_name='زمان مشاهده'),
        ),
    ]
