# Generated by Django 4.2.3 on 2023-11-08 21:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0016_alter_producthit_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producthit',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 9, 0, 39, 27, 332268), verbose_name='زمان مشاهده'),
        ),
    ]
