# Generated by Django 4.2.3 on 2023-09-24 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='map',
            field=models.TextField(blank=True, null=True, verbose_name='نقشه مغازه'),
        ),
    ]
