# Generated by Django 4.2.3 on 2023-09-19 20:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_module', '0001_initial'),
        ('article_module', '0008_alter_articlehit_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='hits_article',
            field=models.ManyToManyField(blank=True, related_name='article_hits', through='article_module.ArticleHit', to='home_module.ipaddress', verbose_name='مشاهده کننده ها'),
        ),
        migrations.AlterField(
            model_name='articlehit',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 20, 0, 18, 30, 599492), verbose_name='تاریخ بازدید'),
        ),
    ]
