# Generated by Django 4.2.3 on 2023-09-20 18:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0010_alter_articlehit_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecomment',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_article', to='article_module.article', verbose_name='مقاله'),
        ),
        migrations.AlterField(
            model_name='articlehit',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 20, 22, 13, 7, 358574), verbose_name='تاریخ بازدید'),
        ),
    ]
