# Generated by Django 4.2.3 on 2023-09-20 20:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0011_alter_articlecomment_article_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlehit',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 20, 23, 57, 35, 697042), verbose_name='تاریخ بازدید'),
        ),
    ]
