# Generated by Django 4.2.3 on 2023-09-20 22:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0012_alter_articlehit_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlehit',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 21, 1, 39, 45, 728886), verbose_name='تاریخ بازدید'),
        ),
    ]
