# Generated by Django 4.2.3 on 2023-09-20 22:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0013_alter_articlehit_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 21, 1, 43, 21, 670871), verbose_name='تاریخ ثبت'),
        ),
        migrations.AlterField(
            model_name='articlehit',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 21, 1, 43, 21, 672864), verbose_name='تاریخ بازدید'),
        ),
    ]
