# Generated by Django 4.2.3 on 2023-09-22 19:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0015_alter_article_created_alter_articlehit_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(max_length=400, verbose_name='عنوان در url'),
        ),
        migrations.AlterField(
            model_name='articlehit',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 22, 23, 25, 6, 378557), verbose_name='تاریخ بازدید'),
        ),
    ]
