# Generated by Django 4.2.3 on 2023-09-24 20:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0019_alter_articlehit_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlehit',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 24, 23, 42, 24, 552473), verbose_name='تاریخ بازدید'),
        ),
    ]
