# Generated by Django 4.2.3 on 2023-10-15 16:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0022_alter_articlehit_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlehit',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 15, 20, 11, 55, 705957), verbose_name='تاریخ بازدید'),
        ),
    ]
