# Generated by Django 4.2.3 on 2023-11-08 21:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0026_alter_articlehit_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlehit',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 9, 0, 39, 27, 363267), verbose_name='تاریخ بازدید'),
        ),
    ]
