# Generated by Django 4.2.3 on 2023-09-24 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0003_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-id'], 'verbose_name': 'کاربر', 'verbose_name_plural': 'کاربر ها'},
        ),
    ]
